# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: cd thoughts
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I write about things that break, things that protect, and how to build better. 
  Also: crypto(graphy), code, or any thoughts worth listing.
baseurl: "" # the subpath of your site, e.g. /blog
domain: yvgny.github.io
url: "https://blog.cdthoughts.ch" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  yvgny
repository: "yvgny/yvgny.github.io"
name: Sacha
logo: "/assets/images/logo.svg"

#
# Configure layouts (add sidebar, wide layout)
#
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      classes: wide

  # homepage (index.html or anything at root)
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      classes: wide

author:
  name: "yvgny"
  bio: >-
    I write about things that break, things that protect, and how to build better. 
    Also: crypto(graphy), code, or any thoughts worth listing.
  avatar   : "/assets/images/bio-photo.jpeg"
  location: "Switzerland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yvgny"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sacha-kozma/"


# Configure homepage pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.0"
minimal_mistakes_skin: "dark" 
plugins:
  - jekyll-include-cache # Required by Minimal Mistakes theme

# Hide the Feed icon/link
atom_feed:
  hide: true

# Configure stats
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-65W5BEKPWZ"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
